export const mockedTestsData = [
  {
    id: "1",
    ratioCaMgK: "",
    ratioNPK: "0.5\n      :1:\n      1.5",
    testCa: "",
    testDate: "28/03/2019",
    testFe: "",
    testGh: "",
    testK: "25",
    testKh: "",
    testMg: "",
    testNo3: "9",
    testPo4: "0.7",
  },
  {
    id: "2",
    ratioCaMgK: "",
    ratioNPK: "0.5\n      :1:\n      1.5",
    testCa: "",
    testDate: "28/03/2016",
    testFe: "",
    testGh: "",
    testK: "20",
    testKh: "",
    testMg: "",
    testNo3: "6",
    testPo4: "0.3",
  },
  {
    id: "3",
    ratioCaMgK: "",
    ratioNPK: "0.5\n      :1:\n      1.5",
    testCa: "",
    testDate: "28/01/2017",
    testFe: "",
    testGh: "",
    testK: "25",
    testKh: "",
    testMg: "",
    testNo3: "2",
    testPo4: "0.1",
  },
  {
    id: "4",
    ratioCaMgK: "",
    ratioNPK: "0.5\n      :1:\n      1.5",
    testCa: "",
    testDate: "28/01/2019",
    testFe: "",
    testGh: "",
    testK: "5",
    testKh: "",
    testMg: "",
    testNo3: "10",
    testPo4: "1",
  },
  {
    id: "5",
    ratioCaMgK: "",
    ratioNPK: "0.5\n      :1:\n      1.5",
    testCa: "",
    testDate: "28/01/2019",
    testFe: "",
    testGh: "",
    testK: "25",
    testKh: "",
    testMg: "",
    testNo3: null,
    testPo4: "1",
  },
];
