export const ADD_WATER_TEST = "ADD_WATER_TEST";
export const EDIT_WATER_TEST = "EDIT_WATER_TEST";
export const DELETE_WATER_TEST = "DELETE_WATER_TEST";

export const EDIT_AQUARIUM_DESCRIPTION = "EDIT_AQUARIUM_DESCRIPTION";

export const ADD_AQUARIUM_EVENT = "ADD_AQUARIUM_EVENT";
export const EDIT_AQUARIUM_EVENT = "EDIT_AQUARIUM_EVENT";
export const DELETE_AQUARIUM_EVENT = "DELETE_AQUARIUM_EVENT";

export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_ERROR = "LOGIN_ERROR";
export const LOGOUT_SUCCESS = "LOGOUT_SUCCESS";
